# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moduls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meetup_id', models.SlugField(unique=True)),
                ('details', models.TextField()),
            ],
        ),
    ]
