# Generated by Django 4.2.7 on 2023-11-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moduls',
            new_name='Meetups',
        ),
    ]
