# Generated by Django 4.2.7 on 2023-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_rename_moduls_meetups'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='image',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
