# Generated by Django 4.2.7 on 2023-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_participant_meetups_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='event_date',
            field=models.DateField(default='2022-06-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetups',
            name='organiser_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
